[livd_publication]
publisher = "AEGLE (local mapping)"
document_identifier = "sysmex_xn350"
publication_version_id = "1.0"
publication_date = "2026-01-19"

# Only the tests explicitly listed below are supported.
# Additional tests and result mappings must be added as needed.

[equipment]
manufacturer = "Sysmex"
model = "XN-350"

# ---------------------------------------
# Result value conversion rules
# ---------------------------------------
# convert can be one of:
#   - none
#   - multiply   (value = value * factor)
#   - divide     (value = value / factor)
#   - add        (value = value + factor)
#   - subtract   (value = value - factor)
#   - log10      (value = log10(value), value > 0 required)
#
# factor:
#   - numeric (number or string)
#   - ignored when convert = "none"

# -----------------------------
# Tests (analysis) mapping
# -----------------------------
[[ivd_test]]
name = "nfs_automate"
vendor_test_code = "NFS_XN3"
lis_test_code = "NFS_XN3"

# -----------------------------
# Result (variable) mapping
# -----------------------------

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^RBC"
lis_result_code = "RBC"
vendor_unit = "10*6/uL"
lis_unit = "million/mm3"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^HGB"
lis_result_code = "HGB"
vendor_unit = "g/dL"
lis_unit = "g/dl"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^HCT"
lis_result_code = "HCT"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^MCV"
lis_result_code = "MCV"
vendor_unit = "fL"
lis_unit = "fl"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^MCH"
lis_result_code = "MCH"
vendor_unit = "pg"
lis_unit = "pg"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^MCHC"
lis_result_code = "MCHC"
vendor_unit = "g/dL"
lis_unit = "g/dl"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^WBC"
lis_result_code = "WBC"
vendor_unit = "10*3/uL"
lis_unit = "10³/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^PLT"
lis_result_code = "PLT"
vendor_unit = "10*3/uL"
lis_unit = "10³/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^NEUT#"
lis_result_code = "NEUT#"
vendor_unit = "10*3/uL"
lis_unit = "10³/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^NEUT%"
lis_result_code = "NEUT%"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^LYMPH#"
lis_result_code = "LYMPH#"
vendor_unit = "10*3/uL"
lis_unit = "10³/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^LYMPH%"
lis_result_code = "LYMPH%"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^MONO#"
lis_result_code = "MONO#"
vendor_unit = "10*3/uL"
lis_unit = "10³/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^MONO%"
lis_result_code = "MONO%"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^EO#"
lis_result_code = "EO#"
vendor_unit = "10*3/uL"
lis_unit = "10³/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^EO%"
lis_result_code = "EO%"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^BASO#"
lis_result_code = "BASO#"
vendor_unit = "10*3/uL"
lis_unit = "10³/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^BASO%"
lis_result_code = "BASO%"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^IG#"
lis_result_code = "IG#"
vendor_unit = "10*3/uL"
lis_unit = "10³/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^IG%"
lis_result_code = "IG%"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^RDW-CV"
lis_result_code = "RDW-CV"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^RDW-SD"
lis_result_code = "RDW-SD"
vendor_unit = "fL"
lis_unit = "fl"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^MICROR"
lis_result_code = "MICROR"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^MACROR"
lis_result_code = "MACROR"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^MPV"
lis_result_code = "MPV"
vendor_unit = "fL"
lis_unit = "fl"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^PDW"
lis_result_code = "PDW"
vendor_unit = "fL"
lis_unit = "fl"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^P-LCR"
lis_result_code = "P-LCR"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^PCT"
lis_result_code = "PCT"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^RET#"
lis_result_code = "RET#"
vendor_unit = "10*6/uL"
lis_unit = "10⁶/µL"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^RET%"
lis_result_code = "RET%"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^IRF"
lis_result_code = "IRF"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^RET-HE"
lis_result_code = "RET-HE"
vendor_unit = "pg"
lis_unit = "pg"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^RBC-HE"
lis_result_code = "RBC-HE"
vendor_unit = "pg"
lis_unit = "pg"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^DELTA-HE"
lis_result_code = "DELTA-HE"
vendor_unit = "pg"
lis_unit = "pg"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^HYPO-HE"
lis_result_code = "HYPO-HE"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^HYPER-HE"
lis_result_code = "HYPER-HE"
vendor_unit = "%"
lis_unit = "%"
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^Neutrophilia"
lis_result_code = "Neutrophil"
vendor_unit = ""
lis_unit = ""
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^Lymphopenia"
lis_result_code = "Lymphopeni"
vendor_unit = ""
lis_unit = ""
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^PLT_Clumps?"
lis_result_code = "PLT_Clumps"
vendor_unit = ""
lis_unit = ""
convert = "none"
factor = 0

[[ivd_mapping]]
test = ""
vendor_result_code = "^^^^Blasts/Abn_Lympho?"
lis_result_code = "Blasts/Abn"
vendor_unit = ""
lis_unit = ""
convert = "none"
factor = 0
